from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


SEVERITIES = ("CRITICAL", "HIGH", "MEDIUM", "LOW")
STATUSES = ("active", "suppressed")
SOURCES = ("working-tree", "git-history", "artifact-hygiene", "external-scanner")
REQUIRED_FINDING_FIELDS = (
    "id",
    "severity",
    "file",
    "line",
    "detector",
    "provider",
    "source",
    "masked_value",
    "status",
)
OUTPUT_FILES = ("security.md", "secrets-found.md", "remediation.md")


@dataclass(frozen=True)
class Finding:
    id: str
    severity: str
    file: str
    line: int
    detector: str
    provider: str
    source: str
    masked_value: str
    status: str = "active"
    secret_type: str = "secret"
    sanitized_snippet: str = ""
    recommended_action: str = "Rotate the exposed credential and remove it from source control."

    def __post_init__(self) -> None:
        validate_finding(self)


def validate_finding(finding: Finding) -> None:
    if finding.severity not in SEVERITIES:
        raise ValueError(f"Unsupported severity: {finding.severity}")
    if finding.status not in STATUSES:
        raise ValueError(f"Unsupported status: {finding.status}")
    if finding.source not in SOURCES:
        raise ValueError(f"Unsupported source: {finding.source}")
    if finding.line < 1:
        raise ValueError("Finding line must be >= 1")
    if not finding.masked_value or "..." not in finding.masked_value:
        raise ValueError("Finding masked_value must use first4...last4 format")


def validate_finding_dict(data: dict) -> list[str]:
    errors: list[str] = []
    missing = [field for field in REQUIRED_FINDING_FIELDS if field not in data]
    errors.extend(f"missing field: {field}" for field in missing)

    if missing:
        return errors

    try:
        Finding(
            id=str(data["id"]),
            severity=str(data["severity"]),
            file=str(data["file"]),
            line=int(data["line"]),
            detector=str(data["detector"]),
            provider=str(data["provider"]),
            source=str(data["source"]),
            masked_value=str(data["masked_value"]),
            status=str(data["status"]),
        )
    except (TypeError, ValueError) as exc:
        errors.append(str(exc))
    return errors


def severity_counts(findings: list[Finding]) -> dict[str, int]:
    return {severity: sum(1 for finding in findings if finding.severity == severity) for severity in SEVERITIES}


def render_finding_entry(finding: Finding) -> str:
    context = finding.sanitized_snippet or "No sanitized context captured."
    return "\n".join(
        [
            f"### {finding.id}: {finding.secret_type}",
            "",
            f"**Location:** `{finding.file}:{finding.line}`",
            f"**Detector:** `{finding.detector}`",
            f"**Provider:** `{finding.provider}`",
            f"**Source:** `{finding.source}`",
            f"**Severity:** `{finding.severity}`",
            f"**Status:** `{finding.status}`",
            "",
            f"**Masked Value:** `{finding.masked_value}`",
            "",
            "**Context:**",
            "```text",
            context,
            "```",
            "",
            f"**Recommended Action:** {finding.recommended_action}",
        ]
    )


def render_secrets_found(findings: list[Finding]) -> str:
    counts = severity_counts(findings)
    sections = [
        "# Secrets Found",
        "",
        "> Detailed report of detected secrets. All values are masked.",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|---|---|",
        f"| Total Findings | {len(findings)} |",
        f"| Critical | {counts['CRITICAL']} |",
        f"| High | {counts['HIGH']} |",
        f"| Medium | {counts['MEDIUM']} |",
        f"| Low / Suppressed | {counts['LOW']} |",
        "",
    ]

    for severity, title in [
        ("CRITICAL", "Critical Findings"),
        ("HIGH", "High Findings"),
        ("MEDIUM", "Medium Findings"),
        ("LOW", "Low / Suppressed Findings"),
    ]:
        severity_findings = [finding for finding in findings if finding.severity == severity]
        sections.extend([f"## {title}", ""])
        if severity_findings:
            sections.extend(render_finding_entry(finding) + "\n" for finding in severity_findings)
        else:
            sections.append("No findings.")
        sections.append("")

    sections.append("*Generated by Sentinel-Scan*")
    return "\n".join(sections)


def report_output_paths(report_dir: str | Path, findings: list[Finding]) -> list[Path]:
    path = Path(report_dir)
    outputs = [path / "security.md"]
    if findings:
        outputs.extend([path / "secrets-found.md", path / "remediation.md"])
    return outputs
